application: %PROJ_NAME%
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: optional

- url: /media
  static_dir: media
  secure: optional

- url: /_media
  static_dir: kay/media
  secure: optional

- url: /_kay/.*
  script: kay/main.py
  login: admin
  secure: optional

- url: /_ah/queue/deferred
    script: $PYTHON_LIB/google/appengine/ext/deferred/
    login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: optional

- url: /.*
  script: kay/main.py
  secure: optional

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (cron\.yaml)|
  (cron\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (^[^\/]+\/tests\.py$)|
  (^[^\/]+\/tests\/.*$)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (docs\/.*)|
  (kay\/management\/.*)|
  )$

